# The format used for the keystore. It could be set to JKS in case it is a JKS file
server:
  ssl:
    key-store-type: "PKCS12"
    key-store: "classpath:test.p12"
    key-store-password: "111111"
    key-alias: "baeldung"
    enabled: true
  port: 443

#email: ${EMAIL:email}
#password: ${PASS:pass}
#from: "TradingView <noreply@tradingview.com>"
bot:
  name: ${NAME:@name}
  token: ${TOKEN:token}
  chatid: ${CHATID:id}
finam:
  host: https://trade-api.finam.ru
  key: ${KEY:key}
  id: ${CLIENTID:clientid}
  code: ${CODE:USDRUBF}
binance:
  key: ${BINANCE_KEY}
  secret: ${BINANCE_SECRET}
  trailingDelta: ${BINANCE_DELTA:2}
  budget: 30.0
storage:
  file: ${PATH:/storage}
